# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"
  config.vm.provider "vmware_desktop" do |v|
    v.vmx['numvcpus'] = 1
    v.vmx['memsize'] = "1024"
  end

  config.vm.define "node-1" do |node|
    node.vm.hostname = "node-1"
  end

  config.vm.define "node-2" do |node|
    node.vm.hostname = "node-2"
  end
end
