# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"
  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 1
    vb.memory = "1024"
  end

  config.vm.define "node-1" do |node|
    node.vm.hostname = "node-1"
    node.vm.network "private_network", ip: "10.11.12.11"
  end

  config.vm.define "node-2" do |node|
    node.vm.hostname = "node-2"
    node.vm.network "private_network", ip: "10.11.12.12"
  end
end
